---
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: circleci/python:3.7.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: pip install --user tox && PYTHONPATH="~/.local/bin" python -m tox -epy37
      - codecov/upload:
          file: tests/coverage.xml
